language: node_js
node_js:
- '12'
env:
  global:
  - DEPLOY_REPOSITORY="git@github.com:konnectors/bitiba.git"
  # REGISTRY_TOKEN(editor=cozy, app=bitiba)
  - secure: k9kgpddzzkrUwx6M2K7UePAearpva/t0ulYXQQAnXGnhmvBjSCPGffK1HtdMdKzIUdMQqPlQ6O5cc8Q6UO4vIBkKKvDeeieB3EmMgqWG+4oYTDLwPDFnCJ7VYcgRkUVeWoUDs4t/5bDYCbtimS7etdRF7TA1ehJHp7iPjw/5itGgxRq4AGW1T1P7UnLj3UevcwCJyOXdkqclwTwbVYYjJvVQ9Rig7YwWSqbJRGmCdjiFFwnVPjtaFNl/LMvKu8IkfJXIv3I9jU6WP5aft7P9dlJFhNvj5uG1z2uNBKhJ/2t0uMAZ1PofyHTtdZFze4Ai4lRO0+hTdGYCpnWGcH3SeKa51O8/VcBmvasJDfRNrCCVm8G/ydveym7F1CdDFO4NRCfBdFMPEiiArxh3nS2EaNpb8nLKr7UDKlx4kt6mAfULFdFsFBoLtDDl6J7ktCpjL5QtVPD6TQ2Et6FUy/TLPGex6OxqnpSc6Va12oCPcDdAyCU1/y6qpq8n9rlwb09s5auzt6brOqo6tKsefaRb6A9j+lTzLB7aAx6lHa8seFumiNMUKMzhuhGUBX/HgdpXj2qnxZKD265CxRtdT930wliKMiNNdEJLsJarxjV5D1ZVLOZblu3HZ9ZW54xZHjO+EP4BrindFpXTP3TBde+Hw74+2oFPG7Hud28BVdKIf+o=
  # MATTERMOST_HOOK_URL
  - secure: FMp6n3ay99u3uB7xK8ABdPP1w1FQyL0veTyXH+yEKNBV2i12H5UiOWrYvaDpFtTegO/b7CIEYDUvrD9ODnc3JW7BrgEZycM7LKhnFLj/JR010RCdnniInYnRfWGDT4wqYk2V2uCiIu4gND5jlaJCKR9j2zJ5pZYyaXWKkDKvgTa67wxawl+xo4c6lwqw0EjLF9OIaNV12blIOqDS8ajntbHm8eBF/cw31BkqEUvKZDOHcwdJqX4GUOxGa5ycoQw1RCSNBv6CAM47iPahzEHS9hNTWAZPVOQB3vDRVeFE0cPdZGVrBYnnCVtX+fbmQCms6EfLAx5UutEc5SBnIKc7KF54rWh53HGzqYqWJ959tlpk5UV5XWVqlCDVH47yJgtVz1Ag/okjZILNmXKyglmXTUKnicNTrbyNKEmiSKSG1WhiOQA2USnXxfISv2Vfy0Ga4kYq6SbVw9TfkGjSIbyRqoo727HOAGTUloYEyR5VrF1DnsyVbDzMgeVAh7UYoUlS43XJTkcbHWYhM/e9xRwk6Hm2ENR2kpgJCJRyRrk5ZgkPXt/8875IelcRKcd5ovJJg18/OfqBE0P7i2PNSIixCWLdIG7ztOXAScT6ho/wNIAa3OqTooAZCYMPfNIbKYHQSZNL+znCnzgqilmFidwUq64bKko0kDISps5lp1rRbu0=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_0a58e3ac1464_key -iv $encrypted_0a58e3ac1464_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
